databases:
  - name: btcforecast-db
    plan: free
    ipAllowList: []

services:
  - type: web
    name: btc-forecast-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api_simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://btcforecast.com,https://www.btcforecast.com"
      - key: CREATE_DEFAULT_USERS
        value: "false"
      - key: API_HOST
        value: "0.0.0.0"
      - key: API_PORT
        value: "8000"
      - key: ENABLE_DOCS
        value: "true"
      - key: RETRAIN_ON_STARTUP
        value: "false"
      - key: MODEL_PATH
        value: "."
      - key: DATABASE_URL
        fromDatabase:
          name: btcforecast-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true 