global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    region: 'global'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Servers - US East
  - job_name: 'api-servers-us-east'
    static_configs:
      - targets:
        - 'api-server-us-east:8000'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: region
        replacement: 'us-east-1'
      - source_labels: [__address__]
        target_label: service
        replacement: 'api-server'

  # API Servers - US West
  - job_name: 'api-servers-us-west'
    static_configs:
      - targets:
        - 'api-server-us-west:8000'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: region
        replacement: 'us-west-2'
      - source_labels: [__address__]
        target_label: service
        replacement: 'api-server'

  # API Servers - EU West
  - job_name: 'api-servers-eu-west'
    static_configs:
      - targets:
        - 'api-server-eu-west:8000'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: region
        replacement: 'eu-west-1'
      - source_labels: [__address__]
        target_label: service
        replacement: 'api-server'

  # Celery Workers
  - job_name: 'celery-workers'
    static_configs:
      - targets:
        - 'celery-worker-us-east:8000'
        - 'celery-worker-us-west:8000'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'celery-worker'

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets:
        - 'redis-primary:6379'
        - 'redis-replica:6379'
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'redis'

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets:
        - 'postgres-primary:5432'
        - 'postgres-replica:5432'
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'postgres'

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets:
        - 'nginx:80'
    metrics_path: '/nginx_status'
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'nginx'

  # HAProxy
  - job_name: 'haproxy'
    static_configs:
      - targets:
        - 'haproxy:8404'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'haproxy'

  # Node Exporter (if running on hosts)
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node-exporter:9100'
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'node-exporter'

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets:
        - 'elasticsearch:9200'
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'elasticsearch'

  # Consul
  - job_name: 'consul'
    static_configs:
      - targets:
        - 'consul-server:8500'
    metrics_path: '/v1/agent/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'consul'

  # Vault
  - job_name: 'vault'
    static_configs:
      - targets:
        - 'vault:8200'
    metrics_path: '/v1/sys/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'vault'

  # Blackbox exporter for external health checks
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - 'https://api.btcforecast.com/health'
        - 'https://api.btcforecast.com/api/v1/health'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115 